version: '3.4'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: WebServer
    ports: 
      - 1414:80
      - 4414:443
    volumes:
      - ./web:/var/www/html
    links:
      - "iotdb"
  iotdb:
    image: mysql:latest
    container_name: iotDB
    environment:
      MYSQL_DATABASE: 'iot'
      MYSQL_USER: 'iot_user'
      MYSQL_PASSWORD: 'init1234'
      MYSQL_ROOT_PASSWORD: 'TiTsPfRoot'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ../IotDB:/var/lib/mysql
      - ./dbScripts/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql

  iotmqtt:
    build:
      context: .
      dockerfile: Dokerfile.ubuntu
    container_name: mqtt
    

volumes:
  db:
  dbScripts:
  web:
  IotDB:
  IotWebApp:


