version: '3.4'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.WebServer
    container_name: WebServer
    ports: 
      - 1414:80
    volumes:
      - ./web:/var/www/html
    links:
      - "iotdb"
  iotdb:
    build:
      context: .
      dockerfile: Dockerfile.iotDB
    container_name: iotDB
    environment:
      MYSQL_DATABASE: 'iot'
      MYSQL_USER: 'iot_user'
      MYSQL_PASSWORD: 'init1234'
      MYSQL_ROOT_PASSWORD: 'TiTsPfRoot'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
      - ./dbScripts/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql

volumes:
  db:
  dbScripts:
  web:


